[package]
name = "Whatsapp-Backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", features = ["macros", "ws"] }
dotenv = "0.15.0"
futures-util = "0.3.31"
mongodb = "3.2.3"
serde = "1.0.219"
tokio = { version = "1.45.0", features = ["full"] }
